// landshark.vue
<!--

                                   ,-
                                 ,'::|
                                /::::|
                              ,'::::o\
           ____........-------,..::?88b                                  ,-' /
   _.--    . . . .      .   .  .  .   `-._                           ,-' .;'
  <. - :::::o......  ...   . . .. . .  .  .  --._                  ,-'. .;'
   `-._  ` `":`:`:`::||||:::::::::::::::::.:. .   --._ ,'|     ,-'.  .;'
        _=--       //'doo.. `````:`:`::::::::::.:.:.:. .`-`._-'.   .;'
            --..__//juuoooooooooooo. ```:`:`:::::::::.:.:..`'`-'..'
                  `-:`oddoooo. ..   ``:`:`:::::::.:.:.:'`-`-'.--'
                       `-..oooo  . .  ```:`:::::.:.:.:.`-'.--'
LANDSHARK BANDSHARK HANDSHARK MANDELBROT

-->

<script>export default { name: 'Landshark' }</script>
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0000 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0001 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0002 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0003 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0004 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0005 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0006 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0007 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0008 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0009 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0010 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0011 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0012 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0013 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0014 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0015 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0016 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0017 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0018 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0019 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0020 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MA

// landshark.svelte
<!--

                                   ,-
                                 ,'::|
                                /::::|
                              ,'::::o\
           ____........-------,..::?88b                                  ,-' /
   _.--    . . . .      .   .  .  .   `-._                           ,-' .;'
  <. - :::::o......  ...   . . .. . .  .  .  --._                  ,-'. .;'
   `-._  ` `":`:`:`::||||:::::::::::::::::.:. .   --._ ,'|     ,-'.  .;'
        _=--       //'doo.. `````:`:`::::::::::.:.:.:. .`-`._-'.   .;'
            --..__//juuoooooooooooo. ```:`:`:::::::::.:.:..`'`-'..'
                  `-:`oddoooo. ..   ``:`:`:::::::.:.:.:'`-`-'.--'
                       `-..oooo  . .  ```:`:::::.:.:.:.`-'.--'
LANDSHARK BANDSHARK HANDSHARK MANDELBROT

-->

<script>let landshark = {}</script>
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0000 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0001 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0002 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0003 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0004 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0005 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0006 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0007 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0008 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0009 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0010 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0011 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0012 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0013 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0014 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0015 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0016 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0017 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0018 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0019 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0020 -->
<!-- LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0021 -->
